name       : kcalc
version    : 18.12.1
release    : 16
source     :
    - https://cdn.download.kde.org/stable/applications/18.12.1/src/kcalc-18.12.1.tar.xz : 237595641224c28a4d91bb132fc0a66807e03b26b9fba874e6ce8f026774ca39
license    : GPL-2.0-or-later
component  : desktop.kde.core
optimize   : lto
libsplit   : no
summary    : Scientific calculator by KDE
description: |
    KCalc is a calculator which offers many more mathematical functions than meet the eye on a first glance.
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - gmp-devel
    - kconfig-devel
    - kconfigwidgets-devel
    - kdoctools-devel
    - kguiaddons-devel
    - ki18n-devel
    - kinit-devel
    - knotifications-devel
    - kxmlgui-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
