name       : kcalc
version    : 20.12.3
release    : 44
source     :
    - https://cdn.download.kde.org/stable/release-service/20.12.3/src/kcalc-20.12.3.tar.xz : 54068a1767f8d96fd507e8969c7b4b71cc61b5e605c7d6b0869c0bac5c0798de
homepage   : https://kde.org/applications/utilities/org.kde.kcalc
license    : GPL-2.0-or-later
component  : desktop.kde.core
summary    : Scientific calculator by KDE
description: |
    KCalc is a calculator which offers many more mathematical functions than meet the eye on a first glance.
optimize   : lto
libsplit   : no
builddeps  :
    - gmp-devel
    - kcrash-devel
    - kdoctools-devel
    - kguiaddons-devel
    - ki18n-devel
    - kinit-devel
    - knotifications-devel
    - kxmlgui-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install

    # remove docs
    rm -rf $installdir/usr/share/doc
