name       : kcalc
version    : 21.08.0
release    : 49
source     :
    - https://cdn.download.kde.org/stable/release-service/21.08.0/src/kcalc-21.08.0.tar.xz : 03da123c15267c135784476c194f4c559888b76ab5311671f92a90a741b8c391
homepage   : https://kde.org/applications/utilities/org.kde.kcalc
license    : GPL-2.0-or-later
component  : desktop.kde.core
summary    : Scientific calculator by KDE
description: |
    KCalc is a calculator which offers many more mathematical functions than meet the eye on a first glance.
optimize   : lto
libsplit   : no
builddeps  :
    - gmp-devel
    - kcrash-devel
    - kdoctools-devel
    - kguiaddons-devel
    - ki18n-devel
    - knotifications-devel
    - kxmlgui-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install

    # remove docs
    rm -rf $installdir/usr/share/doc
