name       : kcalc
version    : 19.04.1
release    : 20
source     :
    - https://cdn.download.kde.org/stable/applications/19.04.1/src/kcalc-19.04.1.tar.xz : 46d992a9e746231b57398b9bcdbe3933f6601e3cee7e3932ccc2e312779a4c91
license    : GPL-2.0-or-later
component  : desktop.kde.core
optimize   : lto
libsplit   : no
summary    : Scientific calculator by KDE
description: |
    KCalc is a calculator which offers many more mathematical functions than meet the eye on a first glance.
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - gmp-devel
    - kconfig-devel
    - kconfigwidgets-devel
    - kcrash-devel
    - kdoctools-devel
    - kguiaddons-devel
    - ki18n-devel
    - kinit-devel
    - knotifications-devel
    - kxmlgui-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
