name       : kcalc
version    : 19.12.0
release    : 28
source     :
    - https://cdn.download.kde.org/stable/release-service/19.12.0/src/kcalc-19.12.0.tar.xz : 437e972c98c6409a8788a0fcdb6f8738e005f9b5f1dc312998325d2a36b33b22
homepage   : https://kde.org/applications/utilities/org.kde.kcalc
license    : GPL-2.0-or-later
component  : desktop.kde.core
optimize   : lto
libsplit   : no
summary    : Scientific calculator by KDE
description: |
    KCalc is a calculator which offers many more mathematical functions than meet the eye on a first glance.
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - gmp-devel
    - kcrash-devel
    - kdoctools-devel
    - kguiaddons-devel
    - ki18n-devel
    - kinit-devel
    - knotifications-devel
    - kxmlgui-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
