name       : kcalc
version    : 17.08.3
release    : 2
source     :
    - https://cdn.download.kde.org/stable/applications/17.08.3/src/kcalc-17.08.3.tar.xz : d569669fd9f14c0bc2a9e16c65188cc174f9bbab972e42273bd2a51db6846132
license    :
    - GPL-2.0
    - LGPL-2.1
component  : desktop.kde
libsplit   : no
summary    : Scientific calculator by KDE
description: |
    KCalc is a calculator which offers many more mathematical functions than meet the eye on a first glance.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - gmp-devel
    - kconfig-devel
    - kconfigwidgets-devel
    - kdoctools-devel
    - kguiaddons-devel
    - ki18n-devel
    - kinit-devel
    - knotifications-devel
    - kxmlgui-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
