name       : kcalc
version    : 17.12.1
release    : 4
source     :
    - https://cdn.download.kde.org/stable/applications/17.12.1/src/kcalc-17.12.1.tar.xz : 414b36be93eaa19f309f6d25471cfe0f573b60160d34e7c073d56db73f735a01
license    :
    - GPL-2.0
    - LGPL-2.1
component  : desktop.kde
optimize   : lto
libsplit   : no
summary    : Scientific calculator by KDE
description: |
    KCalc is a calculator which offers many more mathematical functions than meet the eye on a first glance.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - gmp-devel
    - kconfig-devel
    - kconfigwidgets-devel
    - kdoctools-devel
    - kguiaddons-devel
    - ki18n-devel
    - kinit-devel
    - knotifications-devel
    - kxmlgui-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
