name       : kcalc
version    : 20.04.1
release    : 33
source     :
    - https://cdn.download.kde.org/stable/release-service/20.04.1/src/kcalc-20.04.1.tar.xz : cb90d263b77378a25ba2409618b61dec412a57fb922c7c81a07fe7f1eea32f70
homepage   : https://kde.org/applications/utilities/org.kde.kcalc
license    : GPL-2.0-or-later
component  : desktop.kde.core
optimize   : lto
libsplit   : no
summary    : Scientific calculator by KDE
description: |
    KCalc is a calculator which offers many more mathematical functions than meet the eye on a first glance.
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - gmp-devel
    - kcrash-devel
    - kdoctools-devel
    - kguiaddons-devel
    - ki18n-devel
    - kinit-devel
    - knotifications-devel
    - kxmlgui-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install

    # remove docs
    rm -rf $installdir/usr/share/doc
