name       : kcalc
version    : 18.04.3
release    : 10
source     :
    - https://cdn.download.kde.org/stable/applications/18.04.3/src/kcalc-18.04.3.tar.xz : 3d6b7d143537c0b7069756b281cc93495c1f01325e94182aa65f9183f66a6a0a
license    :
    - GPL-2.0
    - LGPL-2.1
component  : desktop.kde.core
optimize   : lto
libsplit   : no
summary    : Scientific calculator by KDE
description: |
    KCalc is a calculator which offers many more mathematical functions than meet the eye on a first glance.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - gmp-devel
    - kconfig-devel
    - kconfigwidgets-devel
    - kdoctools-devel
    - kguiaddons-devel
    - ki18n-devel
    - kinit-devel
    - knotifications-devel
    - kxmlgui-devel
setup      : |
    %patch -p1 < $pkgfiles/0001-Disable-building-unshipped-code.patch
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
